apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-server
  labels:
    app: go-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-server
  template:
    metadata:
      labels:
        app: go-web-server
    spec:
      containers:
      - name: go-web-server
        image: rajatguptag/go-web-server:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-server
spec:
  selector:
    app: go-web-server
  type: LoadBalancer
  ports:
    - name: http
      port: 8000
      targetPort: 8000