apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: rajatguptag/go-server:1.0

        ports:
        - containerPort: 5000
        env: 
        - name: user
          value: root
        - name: pass
          value: root
        - name: database_url
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: go-server-service
spec:
  selector:
    app: go-server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
